# Generated by Django 5.1.1 on 2024-10-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_payments_payment_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='сумма оплаты'),
        ),
    ]
