# Generated by Django 5.1.1 on 2024-10-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_payments_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='payment_sum',
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_status',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ссылка на оплату'),
        ),
    ]
