# Generated by Django 5.1.1 on 2024-10-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='url_video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на видео урока'),
        ),
    ]
