# Generated by Django 5.1.1 on 2024-10-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_course_create_at_course_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
